### PR TITLE
JNovelClub needs cloudscraper

### PR DESCRIPTION
**Pull request by lsxta**

### CODE REVIEW

**Comment by TAAPArthur** [comment]
(ignore the build failures; they are unrelated to your change)
So your patch looks fine... however I can access j-novelclub without cloudscraper. I'm in the US and testing on Linux. Could you share some info about your environment (country/OS) so I can better understand the problem. If it turns out cloudscraper is needed only in certain situations, I may just make it a setting that can be overridden as needed.

**Comment by TAAPArthur** [comment]
Test errors should be fixed if you rebase on master.
As for this fix, have any thoughts on a setting to globally enable cloudscraper for all servers. If you already have it installed, it may be fine to run all requests through it. The reason that isn't done is to let each server only have the minimum dependencies needed so people can use it with minimal dependencies. Of course hidden dependencies are worse and if the need of cloudscraper varied by region, may have to update the tests

**Comment by lsxta** [comment]
It's not access - it's continued access. E.g. Crunchyroll uses (or used to use) CloudFlare as a CDN, and I'd often see its bot protection screens when manually accessing Crunchyroll. Similarly, here, for the most part it works fine, but when trying to download a number of Manga images in a row, it would fail after 6 or so parts with what looks like maybe it's a captcha prompt from Cloudflare... cloudscraper fixes this issue. Then the only slowdown is the page descrambling.

I had lots of issues using the page de-scrambling. Particularly for novels that have inverse, white-on-black pages. It would often timeout or fail. I found I had better luck exporting from canvas elements. Technically, there's a re-encoding step, but it also doesn't have an extra border of white along the top and left edges. So right now I'm using a variant of a Chrome extension, and I interact with it a bit manually to download the pages I would need. Certainly the two-page manga spreads look better in a canvas element (on the web) than they do from amt, right now.

**Comment by TAAPArthur** [comment]
So I added a new option: always_use_cloudscraper to always use cloudscraper. Like most settings you can enable on a per server basis if you want. The default is disabled. Let me know if this isn't satisfactory to you

As for the de-scrambling... yeah it isn't the best. I couldn't find the descramble key so I manually compare the edges between images and as you point out doesn't work well when the image is mostly the same color. One thing I've noticed is that images for the same chapter that are the same size are often scrambled the same way so if there are a few "normal" images, the whole process can be sped up.

Also if you know of a program that works, if you can figure out how they descramble the image, that method can be imported here.

**Pull request closed without merging**
